services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=development
      - AWS_KEY=${AWS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - ADMIN_PASSWORD=password
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - CAROLINE_EMAIL_ADDRESS=${CAROLINE_EMAIL_ADDRESS}